class selectors {
    
    static UserName = "#user-name"
    static Password = "#password"
    static LoginButton = "#login-button"
    static HomePageTitle = ".app_logo"
    static ErrorMessage = ".error-message-container.error h3"
    static Menu = "#react-burger-menu-btn"
    static LogoutButton = "#logout_sidebar_link"
    static LoginPageTitle = ".login_logo"
    static ProductList = ".inventory_item_name"
    static AddToCart = ".btn.btn_primary.btn_small.btn_inventory"
    static Cart = ".shopping_cart_link"
    static Checkout = "#checkout"
    static FirstName = "#first-name"
    static LastName = "#last-name"
    static ZipCode = "#postal-code"
    static ContinueButton = "#continue"
    static FinishButton = "#finish"
    static CheckoutBanner = ".complete-header"
    static PriceList = ".inventory_item_price"
    static ProductSort = ".product_sort_container"
    static ItemNumberInCart = ".shopping_cart_badge"
    static ProductBackpack = "button[name*=sauce-labs-backpack]"
    static ProductBikelight = "button[name*=sauce-labs-bike-light]"
    static ProductTshirt = "button[name*=sauce-labs-bolt-t-shirt]"
    static ProductJacket = "button[name*=sauce-labs-fleece-jacket]"
    static ProductOnesie = "button[name*=sauce-labs-onesie]"
    static ProductTshirtRed = "button[name*=allthethings]"
    static Subtotal = ".summary_subtotal_label"
    static TaxCalculated = ".summary_tax_label"
    static FullTotal = "div[class*=summary_total_label]"
    static Footer = ".footer"
    static Footer_Twitter = ".social_twitter a"
    static Footer_FB = ".social_facebook a"
    static Footer_Linkedin = ".social_linkedin a"

}

module.exports = selectors
